version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - network_itarget

networks:
  network_itarget:
    driver: bridge
