version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8989:80'
    volumes:
      - ./backend:/var/www
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'db_itarget'
      MYSQL_ROOT_PASSWORD: 'itarget'
      MYSQL_PASSWORD: 'itarget'
      MYSQL_USER: 'itarget'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
